import type { Work } from "./types";

let counter = 0;
export const nextId = () => `w${Date.now()}${counter++}`;

export const seedWorks: Work[] = [
  {
    id: "w1",
    cstId: "CST-000128",
    title: "Dime Que Sí",
    primaryArtist: "Bismarck",
    type: "Single",
    composition: {
      writers: [
        { name: "Bismarck García", share: 50, ipi: "00512345678", publisher: "Prudence" },
        { name: "Juan Pérez", share: null },
      ],
      publisher: "Prudence",
      publisherShares: [
        { name: "Prudence", share: 50 },
        { name: "Other Publisher", share: 50 },
      ],
      pro: "BMI",
      registered: false,
      registrationHistory: [],
    },
    recording: {
      artist: "Bismarck",
      version: "Original",
      isrc: "US-XXX-26-0001",
      audioAttached: true,
      masterOwners: [{ name: "Bismarck García", share: 100 }],
      distributed: true,
    },
    release: {
      status: "Released",
      date: "June 12, 2026",
      upc: "195269481001",
      distributor: "DistroKid",
      platforms: ["Spotify", "Apple Music", "YouTube Music", "Amazon Music"],
      metadataComplete: true,
    },
    activity: [
      { id: "a1", group: "Today", time: "10:42 AM", label: "ISRC added" },
      { id: "a2", group: "Today", time: "10:31 AM", label: "Writer split updated" },
      { id: "a3", group: "Yesterday", time: "4:02 PM", label: "Release linked" },
      { id: "a4", group: "August 20", time: "9:15 AM", label: "Composition created" },
    ],
  },
  {
    id: "w2",
    cstId: "CST-000104",
    title: "Mi Canción",
    primaryArtist: "Bismarck",
    type: "Single",
    composition: {
      writers: [
        { name: "Bismarck García", share: 70, ipi: "00512345678", publisher: "Prudence" },
        { name: "Lucía Mena", share: 30, ipi: "00598765432" },
      ],
      publisher: "Prudence",
      publisherShares: [{ name: "Prudence", share: 100 }],
      pro: "BMI",
      iswc: "T-934.512.881-4",
      registered: true,
      registrationHistory: [{ date: "March 4, 2026", label: "Registered with BMI" }],
    },
    recording: {
      artist: "Bismarck",
      version: "Original",
      isrc: "US-XXX-26-0104",
      audioAttached: true,
      masterOwners: [{ name: "Bismarck García", share: 100 }],
      distributed: false,
    },
    activity: [
      { id: "b1", group: "Yesterday", time: "1:10 PM", label: "Composition registered" },
      { id: "b2", group: "August 12", time: "11:00 AM", label: "Recording created" },
    ],
  },
  {
    id: "w3",
    cstId: "CST-000097",
    title: "Sin Nombre",
    primaryArtist: "Bismarck",
    type: "Instrumental",
    composition: {
      writers: [{ name: "Bismarck García", share: 60 }],
      pro: "BMI",
      registered: false,
      registrationHistory: [],
    },
    recording: {
      artist: "Bismarck",
      version: "Demo",
      audioAttached: true,
      masterOwners: [],
      distributed: false,
    },
    activity: [{ id: "c1", group: "August 2", time: "6:45 PM", label: "Work created" }],
  },
  {
    id: "w4",
    cstId: "CST-000031",
    title: "Old Song",
    primaryArtist: "Bismarck",
    type: "Album track",
    composition: {
      writers: [{ name: "Bismarck García", share: 100, ipi: "00512345678", publisher: "Prudence" }],
      publisher: "Prudence",
      publisherShares: [{ name: "Prudence", share: 100 }],
      pro: "BMI",
      iswc: "T-902.113.554-0",
      registered: true,
      registrationHistory: [{ date: "January 9, 2025", label: "Registered with BMI" }],
    },
    recording: {
      artist: "Bismarck",
      version: "Original",
      isrc: "US-XXX-25-0031",
      audioAttached: true,
      masterOwners: [{ name: "Bismarck García", share: 100 }],
      distributed: true,
    },
    release: {
      status: "Released",
      date: "February 2, 2025",
      upc: "195269480031",
      distributor: "DistroKid",
      platforms: ["Spotify", "Apple Music", "YouTube Music", "Amazon Music"],
      metadataComplete: true,
    },
    activity: [{ id: "d1", group: "February 2, 2025", time: "8:00 AM", label: "Release distributed" }],
  },
  {
    id: "w5",
    cstId: "CST-000142",
    title: "Otra Canción",
    primaryArtist: "Lucía Mena",
    type: "Single",
    composition: {
      writers: [
        { name: "Lucía Mena", share: 50, ipi: "00598765432" },
        { name: "Bismarck García", share: 50, ipi: "00512345678" },
      ],
      publisher: "Prudence",
      publisherShares: [{ name: "Prudence", share: 100 }],
      pro: "ASCAP",
      registered: false,
      registrationHistory: [],
    },
    recording: {
      artist: "Lucía Mena",
      version: "Original",
      isrc: "US-XXX-26-0142",
      audioAttached: true,
      masterOwners: [
        { name: "Lucía Mena", share: 50 },
        { name: "Bismarck García", share: 50 },
      ],
      distributed: true,
    },
    release: {
      status: "Released",
      date: "May 1, 2026",
      distributor: "DistroKid",
      platforms: ["Spotify", "Apple Music"],
      metadataComplete: false,
    },
    activity: [{ id: "e1", group: "May 1, 2026", time: "7:30 AM", label: "Release distributed" }],
  },
  {
    id: "w6",
    cstId: "CST-000155",
    title: "Song X",
    primaryArtist: "Bismarck",
    type: "Single",
    composition: {
      writers: [{ name: "Bismarck García", share: 100, ipi: "00512345678" }],
      publisher: "Prudence",
      pro: "BMI",
      registered: false,
      registrationHistory: [],
    },
    activity: [{ id: "f1", group: "August 24", time: "3:20 PM", label: "Composition created" }],
  },
  {
    id: "w7",
    cstId: "CST-000160",
    title: "Night Drive",
    primaryArtist: "Bismarck",
    type: "Single",
    recording: {
      artist: "Bismarck",
      version: "Original",
      isrc: "US-XXX-26-0160",
      audioAttached: true,
      masterOwners: [{ name: "Bismarck García", share: 100 }],
      distributed: false,
    },
    release: {
      status: "Planned",
      date: "October 3, 2026",
      platforms: [],
      metadataComplete: false,
    },
    activity: [{ id: "g1", group: "August 26", time: "10:05 AM", label: "Recording created" }],
  },
];
